name: universityfinder
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^8.0.0
  http: ^1.1.0
  dartz: ^0.10.1
  connectivity_plus: ^4.0.2
  shared_preferences: ^2.1.1
  dio: ^5.9.0
  equatable: ^2.0.5
  flutter_riverpod: ^2.4.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner: ^2.4.5
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/uniguide_logo.png

  fonts:
    - family: PlayfairDisplay Regular
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Regular.ttf
    - family: PlayfairDisplay Italic
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Italic.ttf
    - family: PlayfairDisplay Bold
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Bold.ttf
